version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/static"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/api"
    schedule:
      interval: "daily"
  
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"